const currencies = [
  {
    order: 1,
    country: 'Argentina',
    name: 'Peso Argentino',
    symbol: '$',
    code: 'ARS',
    value: 0.00478541,
  },
  {
    order: 2,
    country: 'Bolivia',
    name: 'Boliviano',
    symbol: '$b',
    code: 'BOB',
    value: 0.144215,
  },
  {
    order: 3,
    country: 'Brasil',
    name: 'Real Brasileiro',
    symbol: 'R$',
    code: 'BRL',
    value: 0.197441,
  },
  {
    order: 4,
    country: 'Chile',
    name: 'Peso Chileno',
    symbol: '$',
    code: 'CLP',
    value: 0.00125545,
  },
  {
    order: 5,
    country: 'Colombia',
    name: 'Peso Colombiano',
    symbol: '$',
    code: 'COP',
    value: 0.000214940,
  },
  {
    order: 6,
    country: 'Costa Rica',
    name: 'Colón Costarricense',
    symbol: '₡',
    code: 'CRC',
    value: 0.00183434,
  },
  {
    order: 7,
    country: 'Cuba',
    name: 'Peso Cubano',
    symbol: '$',
    code: 'CUP',
    value: 0.0417251,
  },
  {
    order: 8,
    country: 'Ecuador',
    name: 'Dolar Estadounidense',
    symbol: '$',
    code: 'USD',
    value: 1,
  },
  {
    order: 9,
    country: 'El Salvador',
    name: 'Colón Salvadoreño',
    symbol: '$',
    code: 'SVC',
    value: 0.114286,
  },
  {
    order: 10,
    country: 'Guatemala',
    name: 'Quetzal Guatemalteco',
    symbol: 'Q',
    code: 'GTQ',
    value: 0.128165,
  },
  {
    order: 11,
    country: 'Haiti',
    name: 'Gourde haitiano',
    symbol: 'G',
    code: 'HTG',
    value: 0.00643189,
  },
  {
    order: 12,
    country: 'Honduras',
    name: 'Lempira Hondureño',
    symbol: 'L',
    code: 'HNL',
    value: 0.0406492,
  },
  {
    order: 13,
    country: 'Mexico',
    name: 'Peso Mexicano',
    symbol: '$',
    code: 'MXN',
    value: 0.0554879,
  },
  {
    order: 14,
    country: 'Nicaragua',
    name: 'Córdoba Nicaragüense',
    symbol: 'C$',
    code: 'NIO',
    value: 0.0273411,
  },
  {
    order: 15,
    country: 'Panama',
    name: 'Balboa Panameña',
    symbol: 'B/.',
    code: 'PAB',
    value: 1,
  },
  {
    order: 16,
    country: 'Paraguay',
    name: 'Guaraní Paraguayo',
    symbol: '₲',
    code: 'PYG',
    value: 0.000139095,
  },
  {
    order: 17,
    country: 'Peru',
    name: 'Sol Peruano',
    symbol: 'S/.',
    code: 'PEN',
    value: 0.265718,
  },
  {
    order: 18,
    country: 'Republica Dominicana',
    name: 'Peso Dominicano',
    symbol: 'RD$',
    code: 'DOP',
    value: 0.0182383,
  },
  {
    order: 19,
    country: 'Uruguay',
    name: 'Peso Uruguayo',
    symbol: '$U',
    code: 'UYU',
    value: 0.0256959,
  },
  {
    order: 20,
    country: 'Venezuela',
    name: 'Bolívar Venezolano',
    symbol: 'Bs',
    code: 'VEF',
    value: 0.000000409151,
  },
]

export default currencies;
